// == Import

// == Composant
function Cgu() {
  return (
    <div className="shadow-md">
      <h1 className="home-title">Conditions générales d'utilisation & Politique de confidentialité</h1>
      <form className="home-title">
        <p className="text-base text-left text-white">La navigation sur les pages du site Web « GameFriendZ » est possible sans obligation de fournir une quelconque information personnelle. Cependant, si une fonctionnalité sur le site requiert l’utilisation d’un service tiers, le traitement de données personnelles pourrait être nécessaire. Si le traitement de données personnelles est nécessaire et qu’il n’existe aucune base légale pour un tel traitement alors nous sollicitons le consentement de l’utilisateur concerné.Par la présente déclaration de protection des données, nous souhaitons informer le grand public de la nature, de l’étendue et de la finalité des données personnelles que nous collectons, utilisons et traitons. En outre, les personnes concernées sont informées, au moyen de cette déclaration de protection des données, des droits auxquels elles ont droit.</p>
        <br />
        <p className="text-base text-left text-white">Site : Le site définit le site web www.gamefriendz.com. Données personnelles : Par données à caractère personnel, on entend toute information concernant une personne physique identifiée ou identifiable (« personne concernée »). Une personne physique identifiable est une personne qui peut être identifiée, directement ou indirectement, notamment par référence à un identifiant tel qu’un nom, un numéro d’identification, des données de localisation, un identifiant en ligne ou à un ou plusieurs facteurs spécifiques liés à l’identité physique, physiologique, génétique, mentale, économique, économique, culturelle ou sociale de cette personne physique. Personnes concernées : La personne concernée est toute personne physique identifiée ou identifiable, dont les données à caractère personnel sont traitées par le responsable du traitement. Traitement : Le traitement est toute opération ou ensemble d’opérations effectuées sur des données à caractère personnel ou sur des ensembles de données à caractère personnel, que ce soit ou non par des moyens automatisés, tels que la collecte, l’enregistrement, l’organisation, la structuration, le stockage, l’adaptation ou la modification, la récupération, la consultation, l’utilisation, la divulgation par transmission, la diffusion ou toute autre forme de mise à disposition, l’alignement ou la combinaison, la restriction, la suppression ou la destruction.</p>
        <br />
        <p className="text-base text-left text-white">Restriction du traitement : La limitation du traitement est le marquage des données personnelles stockées dans le but de limiter leur traitement à l’avenir.Contrôleur responsable du traitement : Le responsable du traitement est la personne physique ou morale, l’autorité publique, l’agence ou tout autre organisme qui, seul ou conjointement avec d’autres, détermine les finalités et les moyens du traitement des données à caractère personnel ; lorsque les finalités et les moyens de ce traitement sont déterminés par le droit de l’Union ou de l’État membre, le responsable du traitement ou les critères spécifiques de sa désignation peuvent être prévus par le droit de l’Union ou de l’État membre. Sous-traitant : Le sous-traitant est une personne physique ou morale, une autorité publique, une agence ou tout autre organisme qui traite des données à caractère personnel pour le compte du responsable du traitement. Destinataire (d’un traitement de données) : Le destinataire est une personne physique ou morale, une autorité publique, une agence ou un autre organisme auquel les données personnelles sont communiquées, qu’il s’agisse d’un tiers ou non. Toutefois, les autorités publiques qui peuvent recevoir des données à caractère personnel dans le cadre d’une enquête particulière conformément au droit de l’Union ou de l’État membre ne sont pas considérées comme des destinataires ; le traitement de ces données par ces autorités publiques se fait dans le respect des règles applicables en matière de protection des données, conformément aux finalités du traitement.</p>
        <br />
        <p className="text-base text-left text-white">Tiers : Un tiers est une personne physique ou morale, une autorité publique, une agence ou un organisme autre que la personne concernée, le responsable du traitement, le sous-traitant et les personnes qui, sous l’autorité directe du responsable du traitement ou du sous-traitant, sont autorisées à traiter des données à caractère personnel. Consentement explicite : Le consentement de la personne concernée est toute indication librement donnée, spécifique, informée et sans ambigüité de la volonté de la personne concernée, par laquelle celle-ci, par une déclaration ou par une action affirmative claire, signifie son consentement au traitement des données à caractère personnel la concernant.</p>
      </form>
    </div>
  );
}

// == Export
export default Cgu;
